name: Build
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  Build-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3.2.0
      - name: Install node
        uses: actions/setup-node@v3.5.1
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run compile
