name: Release
on:
  release:
    types:
    - created
jobs:
  Publish_extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3.2.0
      - name: Install node
        uses: actions/setup-node@v3.5.1
      - name: Install dependencies
        run: npm install
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Publish
        env:
          PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish --pat "$PAT"
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file: automatask-*.vsix
