name: Release
on:
  push:
    branches:
    - release
  release:
    types:
    - created
jobs:
  Publish_extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3.2.0
      - name: Install node
        uses: actions/setup-node@v3.5.1
      - name: Install dependencies
        run: npm install
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Publish
        run: vsce publish --pat ${{ secrets.VSCE_PAT }}
